"""change

Revision ID: 957d16bf240b
Revises: 8ea06a2cea0d
Create Date: 2023-11-14 22:52:48.818579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957d16bf240b'
down_revision = '8ea06a2cea0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id_user'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
