"""Initial migration

Revision ID: 9ca4ebc9b992
Revises: e38cf209b6b1
Create Date: 2023-11-20 10:27:37.883719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca4ebc9b992'
down_revision = 'e38cf209b6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('traders', schema=None) as batch_op:
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
