"""Initial migration

Revision ID: e38cf209b6b1
Revises: 
Create Date: 2023-11-20 10:22:01.957070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38cf209b6b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('category',
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_table('traders',
    sa.Column('trader_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('trader_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Traderlocation',
    sa.Column('cord_id', sa.Integer(), nullable=False),
    sa.Column('trader_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(precision=100), nullable=False),
    sa.Column('longitude', sa.Float(precision=100), nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.trader_id'], ),
    sa.PrimaryKeyConstraint('cord_id')
    )
    op.create_table('product',
    sa.Column('pro_id', sa.Integer(), nullable=False),
    sa.Column('pro_name', sa.String(length=100), nullable=False),
    sa.Column('pro_dec', sa.String(length=300), nullable=False),
    sa.Column('pro_cont', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.cat_id'], ),
    sa.PrimaryKeyConstraint('pro_id')
    )
    op.create_table('trader_category_association',
    sa.Column('trader_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.cat_id'], ),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.trader_id'], )
    )
    op.create_table('userlocation',
    sa.Column('cord_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(precision=100), nullable=False),
    sa.Column('longitude', sa.Float(precision=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('cord_id')
    )
    op.create_table('product_category_association',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.cat_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.pro_id'], )
    )
    op.create_table('trader_product_association',
    sa.Column('trader_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.pro_id'], ),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.trader_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trader_product_association')
    op.drop_table('product_category_association')
    op.drop_table('userlocation')
    op.drop_table('trader_category_association')
    op.drop_table('product')
    op.drop_table('Traderlocation')
    op.drop_table('users')
    op.drop_table('traders')
    op.drop_table('category')
    op.drop_table('admin')
    # ### end Alembic commands ###
